# Generated by Django 4.2.13 on 2024-06-01 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_alter_comment_created_date_alter_post_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 15, 40, 26, 765365)),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 15, 40, 26, 765365)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 15, 40, 26, 765365)),
        ),
    ]
