# Generated by Django 4.2.13 on 2024-06-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0007_remove_comment_approved_comment_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
